# Generated by Django 2.1.2 on 2018-11-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181106_2343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraperequest',
            table='scrape_requests',
        ),
        migrations.AlterModelTable(
            name='scraperesult',
            table='scrape_results',
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='symbols',
        ),
    ]
