# Generated by Django 2.1.2 on 2018-11-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181106_2351'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraperequest',
            table='app_scrape_requests',
        ),
        migrations.AlterModelTable(
            name='scraperesult',
            table='app_scrape_results',
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='app_symbols',
        ),
    ]
