# Generated by Django 2.1.3 on 2018-11-12 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181111_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
        migrations.AlterModelOptions(
            name='scraperequest',
            options={'verbose_name_plural': 'Scrape Requests'},
        ),
        migrations.AlterModelOptions(
            name='scraperesult',
            options={'verbose_name_plural': 'Scrape Results'},
        ),
        migrations.AlterField(
            model_name='scraperequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
