# Generated by Django 2.1.3 on 2018-11-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181112_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
