# Generated by Django 2.1.3 on 2018-11-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_scraperesult_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperesult',
            old_name='scrape_request_id',
            new_name='scrape_request',
        ),
    ]
