# Generated by Django 2.1.3 on 2018-11-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181113_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperequest',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
