# Generated by Django 2.1.3 on 2018-11-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_scraperesult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
